### PR TITLE
EditCommand: fix bug for duplicate meeting

### LINKED ISSUE #109: edit function v2.0
make sure we cannot put same date as other people

### PR DESCRIPTION
**Pull request by jimseah-0116**
Fixed bug with edit command

Closes #109

### CODE REVIEW

**Review by youdonnnn — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -90,6 +91,12 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_PERSON);
         }
 
+        for (Person person : model.getAddressBook().getPersonList()) {
```
Comment (irwynliong) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:94]: WOW JIM 
if not for you i would have not caught it! 👨🏿

**Review by irwynliong — APPROVED** [review]
LGTM! my lil n
